language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - SPHINX_VERSION=">=1.4, <1.5"
  - SPHINX_VERSION=">=1.5, <1.6"
  - SPHINX_VERSION=">=1.6, <1.7"
  - SPHINX_VERSION=">=1.7, <1.8"
  - SPHINX_VERSION=">=1.8, <1.9"
  - SPHINX_VERSION=">=2.0, <2.1"
  - SPHINX_VERSION=">=2.1, <2.2"
  - SPHINX_VERSION=">=2.2, <2.3"

matrix:
  exclude:
  - python: "2.7"
    env: SPHINX_VERSION=">=1.9, <2.0"
  - python: "2.7"
    env: SPHINX_VERSION=">=2.0, <2.1"
  - python: "2.7"
    env: SPHINX_VERSION=">=2.1, <2.2"
  - python: "2.7"
    env: SPHINX_VERSION=">=2.2, <2.3"

install:
 - pip install "sphinx $SPHINX_VERSION"

script:
 - python setup.py install
 - make test
